version: '3.3'

volumes: 
  db-data:

services:
  phrase-db:
    image: postgres:14.2-alpine
    container_name: phrase-forge-db
    volumes:
      - db-data:/var/lib/postgresql/data   
    env_file:
      - .env
    ports:
      - "5434:5432"

  phrase-api:
    build: .
    container_name: phrase-forge-api
    user: node
    env_file:
       - .env
    volumes:
       - ./:/home/node/app
    ports: 
       - "3001:3000"




     
